class Sound:
    def queue_sound(self, path: str, repeat: bool = False) -> None: ...
    def set_volume(self, volume: float = 1.0) -> None: ...
    def play(self) -> None: ...
    def pause(self) -> None: ...

class AudioPlayer:
    def __init__(self) -> None: ...
    def new_sound(self) -> Sound: ...
